# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thrid_login_native' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThridLoginDemo
  pod 'LineSDKSwift', '~> 5.8.2'  # pod 'LineSDK', '~> 5.0.2'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'  # google 登录
end
